### ISSUE TITLE
Dropout is not applied

### ISSUE THREAD

**Issue by goulou** [evintunador/templateGPT#1]
I just came randomly to your code, and think I spotted a mistake.

Correct me if I'm wrong, but without the "inplace=True" argument to F.dropout, one should write `dx = F.dropout(dx, self.dropout_rate)` in mlp_connect and attn_connect functions in layer.py.

https://github.com/evintunador/templateGPT/blob/f5d0f2e385dabd5bf115215d831072e21a2ce168/modules/layer.py#L76
https://github.com/evintunador/templateGPT/blob/f5d0f2e385dabd5bf115215d831072e21a2ce168/modules/layer.py#L83

See https://pytorch.org/docs/stable/_modules/torch/nn/functional.html#dropout for the default value (False) of `inplace`

**Comment by evintunador** [comment]
good catch, thanks! I also probably need to think more about where specifically in the model I want dropout to be occurring; I've got it in almost every possible place right now which might be a bit overkill. Expect updates to this repo in a couple weeks if not days, most notably being distributed data parallel for running on multiple GPUs
